#!/bin/bash
set -e
if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
  systemctl stop vpntoris-native.service 2>/dev/null || true
  systemctl disable vpntoris-native.service 2>/dev/null || true
fi
